{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "HumanResourcesPlatform.WebApi",
    "version" : "1.1"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "paths" : { },
  "components" : {
    "schemas" : {
      "Employer" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identificacao",
            "nullable" : false
          },
          "name" : {
            "type" : "string",
            "description" : "Nome",
            "nullable" : false
          },
          "age" : {
            "type" : "integer",
            "description" : "Idade",
            "format" : "int32",
            "nullable" : false
          },
          "date" : {
            "type" : "string",
            "description" : "Data Inclusao",
            "format" : "date-time",
            "nullable" : false
          }
        }
      },
      "Employe" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identificacao",
            "nullable" : false
          },
          "name" : {
            "type" : "string",
            "description" : "Nome",
            "nullable" : false
          },
          "age" : {
            "type" : "integer",
            "description" : "Idade",
            "format" : "int32",
            "nullable" : false
          },
          "date" : {
            "type" : "string",
            "description" : "Data Inclusao",
            "format" : "date-time",
            "nullable" : false
          }
        }
      },
      "Person" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identificacao",
            "nullable" : false
          },
          "name" : {
            "type" : "string",
            "description" : "Nome",
            "nullable" : false
          },
          "age" : {
            "type" : "integer",
            "description" : "Idade",
            "format" : "int32",
            "nullable" : false
          },
          "date" : {
            "type" : "string",
            "description" : "Data Inclusao",
            "format" : "date-time",
            "nullable" : false
          }
        }
      },
      "Function" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identificacao",
            "nullable" : false
          },
          "name" : {
            "type" : "string",
            "description" : "Nome",
            "nullable" : false
          },
          "age" : {
            "type" : "integer",
            "description" : "Idade",
            "format" : "int32",
            "nullable" : false
          },
          "date" : {
            "type" : "string",
            "description" : "Data Inclusao",
            "format" : "date-time",
            "nullable" : false
          }
        }
      },
      "Rubric" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identificacao",
            "nullable" : false
          },
          "name" : {
            "type" : "string",
            "description" : "Nome",
            "nullable" : false
          },
          "age" : {
            "type" : "integer",
            "description" : "Idade",
            "format" : "int32",
            "nullable" : false
          },
          "date" : {
            "type" : "string",
            "description" : "Data Inclusao",
            "format" : "date-time",
            "nullable" : false
          }
        }
      },
      "Dependent" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identificacao",
            "nullable" : false
          },
          "name" : {
            "type" : "string",
            "description" : "Nome",
            "nullable" : false
          },
          "age" : {
            "type" : "integer",
            "description" : "Idade",
            "format" : "int32",
            "nullable" : false
          },
          "date" : {
            "type" : "string",
            "description" : "Data Inclusao",
            "format" : "date-time",
            "nullable" : false
          }
        }
      },
      "TaxAllotment" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identificacao",
            "nullable" : false
          },
          "name" : {
            "type" : "string",
            "description" : "Nome",
            "nullable" : false
          },
          "age" : {
            "type" : "integer",
            "description" : "Idade",
            "format" : "int32",
            "nullable" : false
          },
          "date" : {
            "type" : "string",
            "description" : "Data Inclusao",
            "format" : "date-time",
            "nullable" : false
          }
        }
      },
      "Syndicate" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identificacao",
            "nullable" : false
          },
          "name" : {
            "type" : "string",
            "description" : "Nome",
            "nullable" : false
          },
          "age" : {
            "type" : "integer",
            "description" : "Idade",
            "format" : "int32",
            "nullable" : false
          },
          "date" : {
            "type" : "string",
            "description" : "Data Inclusao",
            "format" : "date-time",
            "nullable" : false
          }
        }
      }
    }
  }
}